# Generated by Django 6.0.1 on 2026-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled')], default='ACTIVE', max_length=20),
        ),
    ]
